const fs = require('fs');
const path = require('path');

// Custom .env parser to avoid needing 'dotenv' module
function loadEnv() {
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const key = match[1];
        let value = (match[2] || '').trim();
        if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
        if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
        process.env[key] = value;
      }
    });
  }
}

loadEnv();

const OLD_SUPABASE_URL = process.env.OLD_SUPABASE_URL;
const OLD_SUPABASE_SERVICE_ROLE_KEY = process.env.OLD_SUPABASE_SERVICE_ROLE_KEY;

if (!OLD_SUPABASE_URL || !OLD_SUPABASE_SERVICE_ROLE_KEY) {
  console.error("❌ ERROR: Please define OLD_SUPABASE_URL and OLD_SUPABASE_SERVICE_ROLE_KEY in your .env file.");
  process.exit(1);
}

async function main() {
  console.log("🔍 Fetching database definitions from your live Supabase API...");
  
  try {
    const response = await fetch(`${OLD_SUPABASE_URL}/rest/v1/`, {
      headers: {
        'apikey': OLD_SUPABASE_SERVICE_ROLE_KEY,
        'Authorization': `Bearer ${OLD_SUPABASE_SERVICE_ROLE_KEY}`
      }
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch database schema: ${response.statusText}`);
    }

    const schema = await response.json();
    const tables = Object.keys(schema.definitions || {});

    if (tables.length === 0) {
      console.log("⚠️ No tables found in the public schema.");
      return;
    }

    let sql = `-- =========================================================\n`;
    sql += `-- AUTOMATICALLY GENERATED SUPABASE SCHEMA FOR RAHA PREMIUM\n`;
    sql += `-- Paste this SQL script into the SQL Editor of your NEW Supabase project!\n`;
    sql += `-- =========================================================\n\n`;

    // Sort tables so dependencies are resolved if any (optional, but keep simple)
    for (const table of tables) {
      sql += `-- ---------------------------------------------------------\n`;
      sql += `-- Table: "${table}"\n`;
      sql += `-- ---------------------------------------------------------\n`;
      sql += `CREATE TABLE IF NOT EXISTS public."${table}" (\n`;
      
      const properties = schema.definitions[table].properties || {};
      const columns = Object.keys(properties);
      const columnDefs = [];

      for (const col of columns) {
        const prop = properties[col];
        let dbType = 'text'; // fallback type

        // Guess PostgreSQL type based on Swagger OpenAPI specifications
        if (prop.type === 'integer') {
          dbType = 'bigint';
        } else if (prop.type === 'number') {
          dbType = 'numeric';
        } else if (prop.type === 'boolean') {
          dbType = 'boolean';
        } else if (prop.format === 'timestamp with time zone' || col.endsWith('_at')) {
          dbType = 'timestamp with time zone';
        } else if (prop.type === 'array') {
          dbType = 'text[]';
        }

        // Check if primary key
        let pkConstraint = '';
        if (col === 'id') {
          if (prop.type === 'integer') {
            pkConstraint = ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
          } else {
            pkConstraint = ' PRIMARY KEY';
          }
        }

        columnDefs.push(`  "${col}" ${dbType}${pkConstraint}`);
      }

      sql += columnDefs.join(',\n');
      sql += `\n);\n\n`;
    }

    fs.writeFileSync(path.join(__dirname, 'schema.sql'), sql);
    console.log("✅ Database schema generated successfully and saved as 'schema.sql'!");
    console.log("👉 Paste the contents of 'schema.sql' into your new Supabase SQL Editor and run it!");

  } catch (error) {
    console.error("❌ Failed to generate schema:", error.message);
  }
}

main();
